### PR TITLE
train-test splitting for LSTM

### PR DESCRIPTION
**Pull request by gjuresic**
created a function for splitting dict of dfs in train and test sets for LSTM

### CODE REVIEW

**Comment by cristian-castro-a** [comment]
Can we hold this PR for a while? 

For multivariate LSTM I don't know if we have to divide in test and train per predictor df or create a tensor with all the information. I prefer to leave this PR in stand-by and check the example of multivariate LSTM in the documentation. What do you think @gjuresic @swapnalisonkusale and @Tejas-Choudekar ?

**Comment by gjuresic** [comment]
> Can we hold this PR for a while?
> 
> For multivariate LSTM I don't know if we have to divide in test and train per predictor df or create a tensor with all the information. I prefer to leave this PR in stand-by and check the example of multivariate LSTM in the documentation. What do you think @gjuresic @swapnalisonkusale and @Tejas-Choudekar ?

Based on what I have read about multivariate LSTM we can implement it with train test split - but sure let's leave it on-hold.

**Comment by Tejas-Choudekar** [comment]
> Can we hold this PR for a while?
> 
> For multivariate LSTM I don't know if we have to divide in test and train per predictor df or create a tensor with all the information. I prefer to leave this PR in stand-by and check the example of multivariate LSTM in the documentation. What do you think @gjuresic @swapnalisonkusale and @Tejas-Choudekar ?

Even I am not sure about the implementation so I agree with holding it for now

**Comment by swapnalisonkusale** [comment]
> > Can we hold this PR for a while?
> > For multivariate LSTM I don't know if we have to divide in test and train per predictor df or create a tensor with all the information. I prefer to leave this PR in stand-by and check the example of multivariate LSTM in the documentation. What do you think @gjuresic @swapnalisonkusale and @Tejas-Choudekar ?
> 
> Based on what I have read about multivariate LSTM we can implement it with train test split - but sure let's leave it on-hold.

Even I read that we can split into train and test on the documentation page. We can come back again on this later as well.

**Comment by cristian-castro-a** [comment]
> 

Yes we have to do train and test. But the implementation in this function does it by dataframe, instead of doing in a tensor way. For normal ML projects this function would be correct. But for multivariate time series in LSTM I'm not 100% sure. That's my point.

**Pull request closed without merging**
